; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define MyAppName "CBT Editor"
#define MyAppVersion "0.0.21"
#define MyAppPublisher "Yafea"
#define MyAppExeName "CBT Editor.exe"

[Setup]
AppId={{43F3672D-B3E2-4E3E-84DF-892B0E5EE4A6}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
VersionInfoVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputBaseFilename=CBT_Editor_{#MyAppVersion}_setup
OutputDir=Releases
SetupIconFile=yafea.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:";

[Files]
Source: "Publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Registry]
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}"; ValueType: string; ValueName: "ConnectionString"; ValueData: "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA02AVo/nxBUiy56v1x4jTYgQAAAACAAAAAAAQZgAAAAEAACAAAACxAPSWIWS0ij7gDhj53ir0mZSgIwyMuAwHtZVQZPhN6wAAAAAOgAAAAAIAACAAAABbIteFJgCtwG3Juw7m6aEKfH4dM0OVqbLZmHQhAWV6h9AAAADyNtS3S8jphFehu3YMRKTbObY5TF2AVkaOSq2wCsA6wBhg2ZTHa9oNjArWVC1V3tIpi9EE64IPbfrTO/d3W3RRLuyolrcEOnGSuQhwvgRrAy4A5V7qV3Krn59rp6GJlpE8GbJEbX5Nh0nxT4Rtq3l2OyJOKgyyTFFTkYAUvzWJJhZcm55XzRlIGkOup27Ug9wlpW+2XqtpqHu1TI8mVxBMBO2Wq013UtSCWmQBeIYmRhovXOY3YZKb+SCSA3si/YjnPYV6xZts/l5xxiil7v+XQAAAALf3Dt83nsMrN8P9F1mcD429GLeCR7BEIT5wJxZLnqzdfo5OkWGjg/dS1FbAd6iwhFNNeFKijFJ5+5dKznTwetI="; Flags: uninsdeletekey;

[Dirs]
Name: "{commonappdata}\{#MyAppName}\Data";
Name: "{commonappdata}\{#MyAppName}\Output";

[UninstallDelete]
Type: filesandordirs; Name: "{commonappdata}\{#MyAppName}";

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: waituntilterminated postinstall skipifsilent;

